import type { RssFeedConfig } from "./rss/parser";

// Defaults are outlets the in-app reader can actually show: Jina returns
// article text, or the RSS item already carries a full body. Paywalls, bot
// walls, dead endpoints, and feeds that only yield a headline are omitted —
// add those back as user feeds if you still want the headlines.
//
// Invariants (enforced by default-feeds.test.ts): unique ids, http(s) urls,
// authority in 0-100.
export const DEFAULT_FEEDS: RssFeedConfig[] = [
  { id: "adjacent-press", url: "https://adjacent.markets/press/rss", name: "Adjacent Press", category: "general", authority: 82, enabled: true },
  { id: "bbc-business", url: "https://feeds.bbci.co.uk/news/business/rss.xml", name: "BBC Business", category: "general", authority: 80, enabled: true },
  { id: "bbc-world", url: "https://feeds.bbci.co.uk/news/world/rss.xml", name: "BBC World", category: "general", authority: 80, enabled: true },
  { id: "bbc-tech", url: "https://feeds.bbci.co.uk/news/technology/rss.xml", name: "BBC Technology", category: "tech", authority: 74, enabled: true },
  { id: "bbc-science", url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", name: "BBC Science & Environment", category: "general", authority: 72, enabled: true },
  { id: "bbc-politics", url: "https://feeds.bbci.co.uk/news/politics/rss.xml", name: "BBC Politics", category: "geopolitical", authority: 74, enabled: true },
  { id: "guardian-business", url: "https://www.theguardian.com/uk/business/rss", name: "The Guardian Business", category: "general", authority: 76, enabled: true },
  { id: "guardian-economics", url: "https://www.theguardian.com/business/economics/rss", name: "The Guardian Economics", category: "macro", authority: 74, enabled: true },
  { id: "guardian-world", url: "https://www.theguardian.com/world/rss", name: "The Guardian World", category: "general", authority: 76, enabled: true },
  { id: "guardian-tech", url: "https://www.theguardian.com/uk/technology/rss", name: "The Guardian Technology", category: "tech", authority: 70, enabled: true },
  { id: "guardian-money", url: "https://www.theguardian.com/money/rss", name: "The Guardian Money", category: "finance", authority: 66, enabled: true },
  { id: "guardian-us", url: "https://www.theguardian.com/us-news/rss", name: "The Guardian US", category: "general", authority: 72, enabled: true },
  { id: "npr-news", url: "https://feeds.npr.org/1001/rss.xml", name: "NPR News", category: "general", authority: 78, enabled: true },
  { id: "npr-business", url: "https://feeds.npr.org/1006/rss.xml", name: "NPR Business", category: "general", authority: 76, enabled: true },
  { id: "npr-economy", url: "https://feeds.npr.org/1017/rss.xml", name: "NPR Economy", category: "macro", authority: 76, enabled: true },
  { id: "npr-tech", url: "https://feeds.npr.org/1019/rss.xml", name: "NPR Technology", category: "tech", authority: 70, enabled: true },
  { id: "aljazeera-all", url: "https://www.aljazeera.com/xml/rss/all.xml", name: "Al Jazeera", category: "general", authority: 74, enabled: true },
  { id: "cbc-business", url: "https://www.cbc.ca/webfeed/rss/rss-business", name: "CBC Business", category: "general", authority: 72, enabled: true },
  { id: "cbc-world", url: "https://www.cbc.ca/webfeed/rss/rss-world", name: "CBC World", category: "general", authority: 72, enabled: true },
  { id: "dw-business", url: "https://rss.dw.com/rdf/rss-en-bus", name: "Deutsche Welle Business", category: "general", authority: 72, enabled: true },
  { id: "france24-business", url: "https://www.france24.com/en/business/rss", name: "France 24 Business", category: "general", authority: 70, enabled: true },
  { id: "abc-au-business", url: "https://www.abc.net.au/news/feed/51892/rss.xml", name: "ABC Australia Business", category: "general", authority: 70, enabled: true },
  { id: "japan-times", url: "https://www.japantimes.co.jp/feed/", name: "The Japan Times", category: "general", authority: 70, enabled: true },
  { id: "nikkei-asia", url: "https://asia.nikkei.com/rss/feed/nar", name: "Nikkei Asia", category: "general", authority: 78, enabled: true },
  { id: "yahoo-finance", url: "https://finance.yahoo.com/news/rssindex", name: "Yahoo Finance", category: "general", authority: 72, enabled: true },
  { id: "motley-fool", url: "https://www.fool.com/feeds/index.aspx", name: "The Motley Fool", category: "general", authority: 55, enabled: true },
  { id: "business-insider-markets", url: "https://markets.businessinsider.com/rss/news", name: "Business Insider Markets", category: "finance", authority: 62, enabled: true },
  { id: "benzinga", url: "https://www.benzinga.com/feed", name: "Benzinga", category: "finance", authority: 58, enabled: true },
  { id: "the-street", url: "https://www.thestreet.com/.rss/full/", name: "TheStreet", category: "finance", authority: 60, enabled: true },
  { id: "kiplinger", url: "https://www.kiplinger.com/rss", name: "Kiplinger", category: "finance", authority: 60, enabled: true },
  { id: "forbes-business", url: "https://www.forbes.com/business/feed/", name: "Forbes Business", category: "general", authority: 66, enabled: true },
  { id: "forbes-markets", url: "https://www.forbes.com/markets/feed/", name: "Forbes Markets", category: "finance", authority: 66, enabled: true },
  { id: "forbes-money", url: "https://www.forbes.com/money/feed/", name: "Forbes Money", category: "finance", authority: 64, enabled: true },
  { id: "fortune", url: "https://fortune.com/feed/", name: "Fortune", category: "general", authority: 70, enabled: true },
  { id: "money-com", url: "https://money.com/feed/", name: "Money", category: "finance", authority: 56, enabled: true },
  { id: "calculated-risk", url: "https://feeds.feedburner.com/CalculatedRisk", name: "Calculated Risk", category: "macro", authority: 62, enabled: true },
  { id: "ritholtz", url: "https://ritholtz.com/feed/", name: "The Big Picture", category: "finance", authority: 60, enabled: true },
  { id: "abnormal-returns", url: "https://abnormalreturns.com/feed/", name: "Abnormal Returns", category: "finance", authority: 58, enabled: true },
  { id: "wealth-common-sense", url: "https://awealthofcommonsense.com/feed/", name: "A Wealth of Common Sense", category: "finance", authority: 58, enabled: true },
  { id: "marginal-revolution", url: "https://marginalrevolution.com/feed", name: "Marginal Revolution", category: "macro", authority: 60, enabled: true },
  { id: "econbrowser", url: "https://econbrowser.com/feed", name: "Econbrowser", category: "macro", authority: 58, enabled: true },
  { id: "fed-press", url: "https://www.federalreserve.gov/feeds/press_all.xml", name: "Federal Reserve", category: "macro", authority: 95, enabled: true },
  { id: "fed-monetary", url: "https://www.federalreserve.gov/feeds/press_monetary.xml", name: "Fed Monetary Policy", category: "macro", authority: 95, enabled: true },
  { id: "fed-speeches", url: "https://www.federalreserve.gov/feeds/speeches.xml", name: "Fed Speeches", category: "macro", authority: 92, enabled: true },
  { id: "fed-testimony", url: "https://www.federalreserve.gov/feeds/testimony.xml", name: "Fed Testimony", category: "macro", authority: 90, enabled: true },
  { id: "fred-blog", url: "https://fredblog.stlouisfed.org/feed/", name: "FRED Blog", category: "macro", authority: 80, enabled: true },
  { id: "sec-press", url: "https://www.sec.gov/news/pressreleases.rss", name: "SEC Press Releases", category: "finance", authority: 90, enabled: true },
  { id: "sec-litigation", url: "https://www.sec.gov/rss/litigation/litreleases.xml", name: "SEC Litigation", category: "finance", authority: 86, enabled: true },
  { id: "bls-latest", url: "https://www.bls.gov/feed/bls_latest.rss", name: "BLS Releases", category: "macro", authority: 90, enabled: true },
  { id: "bls-cpi", url: "https://www.bls.gov/feed/cpi.rss", name: "BLS Consumer Prices (CPI)", category: "macro", authority: 92, enabled: true },
  { id: "bls-empsit", url: "https://www.bls.gov/feed/empsit.rss", name: "BLS Employment Situation", category: "macro", authority: 92, enabled: true },
  { id: "bls-ppi", url: "https://www.bls.gov/feed/ppi.rss", name: "BLS Producer Prices (PPI)", category: "macro", authority: 90, enabled: true },
  { id: "bls-jolts", url: "https://www.bls.gov/feed/jolts.rss", name: "BLS Job Openings (JOLTS)", category: "macro", authority: 90, enabled: true },
  { id: "bank-of-england", url: "https://www.bankofengland.co.uk/rss/news", name: "Bank of England", category: "macro", authority: 90, enabled: true },
  { id: "fda-press", url: "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/press-releases/rss.xml", name: "FDA Press Releases", category: "healthcare", authority: 88, enabled: true },
  { id: "eia-today", url: "https://www.eia.gov/rss/todayinenergy.xml", name: "EIA Today in Energy", category: "energy", authority: 88, enabled: true },
  { id: "eia-press", url: "https://www.eia.gov/rss/press_releases.xml", name: "EIA Press Releases", category: "energy", authority: 86, enabled: true },
  { id: "ars-technica", url: "https://feeds.arstechnica.com/arstechnica/index", name: "Ars Technica", category: "tech", authority: 70, enabled: true },
  { id: "the-verge", url: "https://www.theverge.com/rss/index.xml", name: "The Verge", category: "tech", authority: 64, enabled: true },
  { id: "wired", url: "https://www.wired.com/feed/rss", name: "WIRED", category: "tech", authority: 70, enabled: true },
  { id: "mit-tech-review", url: "https://www.technologyreview.com/feed/", name: "MIT Technology Review", category: "tech", authority: 76, enabled: true },
  { id: "venturebeat", url: "https://venturebeat.com/feed/", name: "VentureBeat", category: "tech", authority: 64, enabled: true },
  { id: "the-register", url: "https://www.theregister.com/headlines.atom", name: "The Register", category: "tech", authority: 66, enabled: true },
  { id: "macrumors", url: "https://feeds.macrumors.com/MacRumors-All", name: "MacRumors", category: "tech", authority: 58, enabled: true },
  { id: "techradar", url: "https://www.techradar.com/rss", name: "TechRadar", category: "tech", authority: 58, enabled: true },
  { id: "toms-hardware", url: "https://www.tomshardware.com/feeds/all", name: "Tom's Hardware", category: "tech", authority: 60, enabled: true },
  { id: "ieee-spectrum", url: "https://spectrum.ieee.org/feeds/feed.rss", name: "IEEE Spectrum", category: "tech", authority: 72, enabled: true },
  { id: "slashdot", url: "https://rss.slashdot.org/Slashdot/slashdotMain", name: "Slashdot", category: "tech", authority: 56, enabled: true },
  { id: "krebs-on-security", url: "https://krebsonsecurity.com/feed/", name: "Krebs on Security", category: "tech", authority: 70, enabled: true },
  { id: "nvidia-blog", url: "https://blogs.nvidia.com/feed/", name: "NVIDIA Blog", category: "tech", authority: 68, enabled: true },
  { id: "aws-ml-blog", url: "https://aws.amazon.com/blogs/machine-learning/feed/", name: "AWS Machine Learning", category: "tech", authority: 66, enabled: true },
  { id: "import-ai", url: "https://jack-clark.net/feed/", name: "Import AI", category: "tech", authority: 62, enabled: true },
  { id: "oilprice", url: "https://oilprice.com/rss/main", name: "OilPrice.com", category: "energy", authority: 66, enabled: true },
  { id: "power-magazine", url: "https://www.powermag.com/feed/", name: "POWER Magazine", category: "energy", authority: 60, enabled: true },
  { id: "pv-magazine", url: "https://www.pv-magazine.com/feed/", name: "pv magazine", category: "energy", authority: 60, enabled: true },
  { id: "carbon-brief", url: "https://www.carbonbrief.org/feed/", name: "Carbon Brief", category: "energy", authority: 66, enabled: true },
  { id: "stat-news", url: "https://www.statnews.com/feed/", name: "STAT News", category: "healthcare", authority: 74, enabled: true },
  { id: "bitcoin-magazine", url: "https://bitcoinmagazine.com/feed", name: "Bitcoin Magazine", category: "crypto", authority: 60, enabled: true },
  { id: "defense-news", url: "https://www.defensenews.com/arc/outboundfeeds/rss/?outputType=xml", name: "Defense News", category: "geopolitical", authority: 70, enabled: true },
  { id: "war-on-the-rocks", url: "https://warontherocks.com/feed/", name: "War on the Rocks", category: "geopolitical", authority: 68, enabled: true },
  { id: "financial-post", url: "https://financialpost.com/feed", name: "Financial Post", category: "finance", authority: 68, enabled: true },
  { id: "bbc-us-canada", url: "https://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml", name: "BBC US & Canada", category: "general", authority: 78, enabled: true },
  { id: "bbc-asia", url: "https://feeds.bbci.co.uk/news/world/asia/rss.xml", name: "BBC Asia", category: "general", authority: 76, enabled: true },
  { id: "bbc-europe", url: "https://feeds.bbci.co.uk/news/world/europe/rss.xml", name: "BBC Europe", category: "general", authority: 76, enabled: true },
  { id: "npr-world", url: "https://feeds.npr.org/1004/rss.xml", name: "NPR World", category: "general", authority: 76, enabled: true },
  { id: "npr-politics", url: "https://feeds.npr.org/1014/rss.xml", name: "NPR Politics", category: "geopolitical", authority: 74, enabled: true },
  { id: "guardian-environment", url: "https://www.theguardian.com/environment/rss", name: "The Guardian Environment", category: "energy", authority: 72, enabled: true },
  { id: "guardian-energy", url: "https://www.theguardian.com/environment/energy/rss", name: "The Guardian Energy", category: "energy", authority: 70, enabled: true },
  { id: "valuewalk", url: "https://www.valuewalk.com/feed/", name: "ValueWalk", category: "finance", authority: 54, enabled: true },
  { id: "of-dollars-and-data", url: "https://ofdollarsanddata.com/feed/", name: "Of Dollars And Data", category: "finance", authority: 56, enabled: true },
  { id: "damodaran", url: "https://aswathdamodaran.blogspot.com/feeds/posts/default?alt=rss", name: "Musings on Markets (Damodaran)", category: "finance", authority: 66, enabled: true },
  { id: "monevator", url: "https://monevator.com/feed/", name: "Monevator", category: "finance", authority: 52, enabled: true },
  { id: "dividend-growth-investor", url: "https://www.dividendgrowthinvestor.com/feeds/posts/default?alt=rss", name: "Dividend Growth Investor", category: "finance", authority: 50, enabled: true },
  { id: "404media", url: "https://www.404media.co/rss/", name: "404 Media", category: "tech", authority: 64, enabled: true },
  { id: "semianalysis", url: "https://semianalysis.com/feed/", name: "SemiAnalysis", category: "tech", authority: 70, enabled: true },
  { id: "microsoft-research", url: "https://www.microsoft.com/en-us/research/feed/", name: "Microsoft Research", category: "tech", authority: 66, enabled: true },
  { id: "bair-blog", url: "https://bair.berkeley.edu/blog/feed.xml", name: "Berkeley AI Research", category: "tech", authority: 64, enabled: true },
  { id: "the-gradient", url: "https://thegradient.pub/rss/", name: "The Gradient", category: "tech", authority: 60, enabled: true },
  { id: "climate-home", url: "https://www.climatechangenews.com/feed/", name: "Climate Home News", category: "energy", authority: 58, enabled: true },
  { id: "inside-climate-news", url: "https://insideclimatenews.org/feed/", name: "Inside Climate News", category: "energy", authority: 62, enabled: true },
  { id: "kff-health-news", url: "https://kffhealthnews.org/feed/", name: "KFF Health News", category: "healthcare", authority: 66, enabled: true },
  { id: "science-daily-health", url: "https://www.sciencedaily.com/rss/health_medicine.xml", name: "ScienceDaily Health", category: "healthcare", authority: 58, enabled: true },
  { id: "the-defiant", url: "https://thedefiant.io/feed/", name: "The Defiant", category: "crypto", authority: 58, enabled: true },
  { id: "responsible-statecraft", url: "https://responsiblestatecraft.org/feed/", name: "Responsible Statecraft", category: "geopolitical", authority: 60, enabled: true },
  { id: "la-times-business", url: "https://www.latimes.com/business/rss2.0.xml", name: "Los Angeles Times Business", category: "general", authority: 74, enabled: true },
  { id: "vox", url: "https://www.vox.com/rss/index.xml", name: "Vox", category: "general", authority: 68, enabled: true },
  { id: "the-atlantic-business", url: "https://www.theatlantic.com/feed/channel/business/", name: "The Atlantic Business", category: "general", authority: 72, enabled: true },
  { id: "semiconductor-engineering", url: "https://semiengineering.com/feed/", name: "Semiconductor Engineering", category: "tech", authority: 64, enabled: true },
  { id: "freightwaves", url: "https://www.freightwaves.com/news/feed", name: "FreightWaves", category: "general", authority: 62, enabled: true },
  { id: "power-engineering", url: "https://www.power-eng.com/feed/", name: "Power Engineering", category: "energy", authority: 58, enabled: true },
  { id: "pcworld", url: "https://www.pcworld.com/index.rss", name: "PCWorld", category: "tech", authority: 56, enabled: true },
  { id: "computerworld", url: "https://www.computerworld.com/index.rss", name: "Computerworld", category: "tech", authority: 58, enabled: true },
  { id: "genengnews", url: "https://www.genengnews.com/feed/", name: "GEN (Genetic Engineering News)", category: "healthcare", authority: 62, enabled: true },
  { id: "defense-one", url: "https://www.defenseone.com/rss/all/", name: "Defense One", category: "geopolitical", authority: 66, enabled: true },
  { id: "military-times", url: "https://www.militarytimes.com/arc/outboundfeeds/rss/?outputType=xml", name: "Military Times", category: "geopolitical", authority: 62, enabled: true },
  { id: "fed-orders", url: "https://www.federalreserve.gov/feeds/press_orders.xml", name: "Fed Enforcement Orders", category: "macro", authority: 88, enabled: true },
  { id: "fed-bcreg", url: "https://www.federalreserve.gov/feeds/press_bcreg.xml", name: "Fed Banking Regulation", category: "macro", authority: 88, enabled: true },
  { id: "bls-ces", url: "https://www.bls.gov/feed/ces.rss", name: "BLS Employment (CES)", category: "macro", authority: 88, enabled: true },
  { id: "bls-eci", url: "https://www.bls.gov/feed/eci.rss", name: "BLS Employment Cost Index", category: "macro", authority: 88, enabled: true },
  { id: "cbo", url: "https://www.cbo.gov/publications/all/rss.xml", name: "Congressional Budget Office", category: "macro", authority: 86, enabled: true },
  { id: "cftc", url: "https://www.cftc.gov/RSS/RSSGP/rssgp.xml", name: "CFTC", category: "finance", authority: 86, enabled: true },
  { id: "ny-fed-liberty-street", url: "https://libertystreeteconomics.newyorkfed.org/feed/", name: "NY Fed Liberty Street Economics", category: "macro", authority: 82, enabled: true },
  { id: "fast-company", url: "https://www.fastcompany.com/latest/rss", name: "Fast Company", category: "general", authority: 62, enabled: true },
  { id: "pymnts", url: "https://www.pymnts.com/feed/", name: "PYMNTS", category: "finance", authority: 58, enabled: true },
  { id: "ecb-press", url: "https://www.ecb.europa.eu/rss/press.html", name: "European Central Bank", category: "macro", authority: 90, enabled: true },
  { id: "sec-speeches", url: "https://www.sec.gov/news/speeches-statements.rss", name: "SEC Speeches & Statements", category: "finance", authority: 84, enabled: true },
];
